apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparkleaf-handler
  namespace: mf
spec:
  containers:
  - name: handler
  image: emilsallem/sparkleaf-handler:main-latest
  imagePullPolicy: Never
  nodeSelector:
    pool: ondemand