apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparkleaf-handler
  namespace: mf
  labels:
    app: handler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: handler
  template:
    metadata:
      labels:
        app: handler
    spec:
      containers:
      - name: handler
        image: emilsallem/sparkleaf-handler:main-latest
        ports:
        - containerPort: 80
      nodeSelector:
        agentpool: ondemand