apiVersion: v1
kind: Service
metadata:
  name: sparkleaf-handler
  namespace: mf
spec:
  selector:
    app.kubernetes.io/name: sparkleaf-handler
  ports:
    - protocol: TCP
      name: 
      port: 80
      targetPort: 80
